# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [17]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [18]:
A = np.arange(1, 16).reshape(3,5)

In [19]:
# printar hur många axes/dimension det finns
print(A.ndim)
# printar hur många rader och kolumner det finns
print(A.shape)
# printar hur många element det finns
print(A.size)
# printar vilken datatyp elementerna har
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [20]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [21]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(np.exp(B))
print()
print(np.min(B))
print()
print(np.min(B, axis = 0))
print()
print(np.min(B, axis = 1))
print(np.argmin(B))
print()
print(np.argmin(B, axis = 0))
print()
print(np.sum(B))
print()
print(np.mean(B, axis = 1))
print()
print(np.median(B, axis = 1))


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 2 3]

[1 4 7]
0

[0 0 0]

45

[2. 5. 8.]

[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [24]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [25]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [26]:
print("The missing indices is considered slices")

The missing indices is considered slices


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [27]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
# "i" representerar rader i en array, loopar igenom varje element i en rad i två dimentionell ordning(A)
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [29]:
# Loopar igenom alla element i en en dimensionell ordning(A), så ravel() ändrar 2 dimensionell till en dimensionell
for i in A.ravel():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [30]:
#skapar en array med 30 värden från 0 till 29
a = np.arange(30)
# med reshape ändrar dimension form från en-dimensionell till 3 dimensionell array
b = a.reshape((2, 3, -1))
# en dimensionell array
print(a)
print()
# 3 dimensionell array - 2 array med 3 rader och -1 samma storlek på element som a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [32]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [33]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [34]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [35]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [48]:
def add_mult_matrices(A, B, calculate):
    if not (isinstance(A, np.ndarray) or not isinstance(B, np.ndarray)):
        return "Both input should be of type ndarray"
    if calculate == "add":
        if A.shape == B.shape:
            result = A + B
            return result
        else:
            return "The matrices must have the same shape for addition"
    elif calculate == "multiply":
            if A.shape[1] == B.shape[0]:
                result = np.dot(A, B)
                return result
            else:
                return "Matrices are not comformable for multiplication"
    else:
                return "Invalid calculation"
    print(result)

**Chap2. Question 2**

In [62]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, "multiply")
AC = add_mult_matrices(A, C, "multiply")
AB_eq_AC = np.array_equal(AB, AC)
B_eq_C = np.array_equal(B, C)
print("AB")
print(AB)
print("AC")
print(AC)
print("AB == AC:", AB_eq_AC)
print("B == C:", B_eq_C)

AB
[[ 4  7]
 [ 8 14]]
AC
[[ 4  7]
 [ 8 14]]
AB == AC: True
B == C: False


**Chap2. Question 3**

In [60]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])
AD = add_mult_matrices(A, D, "multiply")
DA = add_mult_matrices(D, A, "multiply")
print("AD")
print(AD)
print("DA")
print(DA)

AD
[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [64]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])
AB = add_mult_matrices(A, B, "multiply")
print("AB")
print(AB)

AB
[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [93]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

inv_A = np.linalg.inv(A)
print(inv_A)

inv_B = np.linalg.inv(B)
print(inv_B)

print(A @ inv_A)
print(np.allclose(A @ inv_A, np.eye(2)))
print(B @ inv_B)
print(np.allclose(B @ inv_B, np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.77635684e-15  1.00000000e+00]]
True
[[1. 0.]
 [0. 1.]]
True


**Quiz p.19, Question 3**

In [95]:
A = np.array([[2, 2], [1, 2]])
inv_A = np.linalg.inv(A)
print(inv_A)
print(A @ inv_A)
print(np.allclose(A @ inv_A, np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [96]:
Matrix = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
result = np.array([-7, 5, 2])

print("Matrix:", Matrix)
print()
print("Result", result)

Matrix: [[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

Result [-7  5  2]


**Chap10. Question 1 b)**

In [97]:
x = np.linalg.solve(Matrix, result)
print(x)

[ 3.  4. -6.]


**Chap 12. Question 1**

In [98]:
matrix = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
result = np.array([1, -1, 1])
# Tar reda på värdet av x
x = np.linalg.solve(matrix, result)
print(x)

[ 8.  2. -1.]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [99]:
# v1 har värden[0, 1, 2. 3]
v1 = np.arange(4)
# v2 är = v1 men slicat till de två sista värdena
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [100]:
# Base attributet för en vy returnerar den ursprungliga matricen medan den returnerar "None" för en kopia.
print(v1.base)
# v2 är en vy av v1
print(v2.base)

None
[0 1 2 3]


In [101]:
# Vi ändrar sista elementet i v2 till 123
v2[-1] = 123
# Det sista elementet i v1 kommer också att ändras eftersom v2 är en vy, vilket innebär att de delar samma dataminne.
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
# När v2 är skapad som en "slice" av v1 så är den inte en copy av v1 utan en view. När man ändrar de sista elementen i v2
# till 123 så ändras också v1 pågrund av att de använder samma data från minnet. ".base" avgör
# om en array är en view eller en copy. Så v2 är en view.
